/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_github_hewking_jnitest_MainActivity */

#ifndef _Included_com_github_hewking_jnitest_MainActivity
#define _Included_com_github_hewking_jnitest_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_github_hewking_jnitest_MainActivity
 * Method:    getStringFromNative
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_github_hewking_jnitest_MainActivity_getStringFromNative
  (JNIEnv *, jobject);

/*
 * Class:     com_github_hewking_jnitest_MainActivity
 * Method:    callJavaMethodFromJni
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_github_hewking_jnitest_MainActivity_callJavaMethodFromJni
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
