/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_dlodlo_cryptlib_EncryptUtil */

#ifndef _Included_com_dlodlo_cryptlib_EncryptUtil
#define _Included_com_dlodlo_cryptlib_EncryptUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_dlodlo_cryptlib_EncryptUtil
 * Method:    clientInit
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_dlodlo_cryptlib_EncryptUtil_clientInit
  (JNIEnv *, jobject);

/*
 * Class:     com_dlodlo_cryptlib_EncryptUtil
 * Method:    clientEncrypt
 * Signature: (Ljava/lang/String;I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_dlodlo_cryptlib_EncryptUtil_clientEncrypt
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     com_dlodlo_cryptlib_EncryptUtil
 * Method:    clientDencrypt
 * Signature: (Ljava/lang/String;II)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_dlodlo_cryptlib_EncryptUtil_clientDencrypt
  (JNIEnv *, jobject, jstring, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
