/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_dlodlo_objectjnidemo_JniObjectActivity */

#ifndef _Included_com_dlodlo_objectjnidemo_JniObjectActivity
#define _Included_com_dlodlo_objectjnidemo_JniObjectActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_dlodlo_objectjnidemo_JniObjectActivity
 * Method:    getStudent
 * Signature: (I)Lcom/dlodlo/objectjnidemo/Student;
 */
JNIEXPORT jobject JNICALL Java_com_dlodlo_objectjnidemo_JniObjectActivity_getStudent
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
