/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_github_hewking_mylibrary_ShareTestActivity */

#ifndef _Included_com_github_hewking_mylibrary_ShareTestActivity
#define _Included_com_github_hewking_mylibrary_ShareTestActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_github_hewking_mylibrary_ShareTestActivity
 * Method:    add
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_github_hewking_mylibrary_ShareTestActivity_add
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_github_hewking_mylibrary_ShareTestActivity
 * Method:    getResult
 * Signature: (I)Lcom/github/hewking/mylibrary/Result;
 */
JNIEXPORT jobject JNICALL Java_com_github_hewking_mylibrary_ShareTestActivity_getResult
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
