/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_github_hewking_encryptlib_EncryptUtil */

#ifndef _Included_com_github_hewking_encryptlib_EncryptUtil
#define _Included_com_github_hewking_encryptlib_EncryptUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_github_hewking_encryptlib_EncryptUtil
 * Method:    clientInit
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_github_hewking_encryptlib_EncryptUtil_clientInit
  (JNIEnv *, jobject);

/*
 * Class:     com_github_hewking_encryptlib_EncryptUtil
 * Method:    clientEncrypt
 * Signature: (Ljava/lang/String;I)Lcom/github/hewking/encryptlib/CryptResult;
 */
JNIEXPORT jobject JNICALL Java_com_github_hewking_encryptlib_EncryptUtil_clientEncrypt
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     com_github_hewking_encryptlib_EncryptUtil
 * Method:    clientDencrypt
 * Signature: (Ljava/lang/String;I)Lcom/github/hewking/encryptlib/CryptResult;
 */
JNIEXPORT jobject JNICALL Java_com_github_hewking_encryptlib_EncryptUtil_clientDencrypt
  (JNIEnv *, jobject, jstring, jint);

#ifdef __cplusplus
}
#endif
#endif
